// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ShoppingList from "./ShoppingList.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Lista de Compras"
                    }),
                JsxRuntime.jsx(ShoppingList.make, {})
              ]
            });
}

var make = App;

export {
  make ,
}
/* ShoppingList Not a pure module */
