// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as JsxRuntime from "react/jsx-runtime";

var style = {
  display: "flex",
  gap: "8px"
};

function ShoppingList(props) {
  var match = React.useState(function () {
        return [];
      });
  var setItems = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setName = match$1[1];
  var name = match$1[0];
  var match$2 = React.useState(function () {
        return "Geral";
      });
  var setCategory = match$2[1];
  var category = match$2[0];
  var addItem = function (param) {
    var trimmed = name.trim();
    if (trimmed === "") {
      return ;
    }
    var newItem_id = Js_math.random_int(0, 999999);
    var newItem = {
      id: newItem_id,
      name: trimmed,
      category: category
    };
    setItems(function (prev) {
          return prev.concat([newItem]);
        });
    setName(function (param) {
          return "";
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("input", {
                              placeholder: "Novo item",
                              value: name,
                              onChange: (function ($$event) {
                                  setName(function (param) {
                                        return $$event.target.value;
                                      });
                                })
                            }),
                        JsxRuntime.jsxs("select", {
                              children: [
                                JsxRuntime.jsx("option", {
                                      children: "Geral",
                                      value: "Geral"
                                    }),
                                JsxRuntime.jsx("option", {
                                      children: "Mercado",
                                      value: "Mercado"
                                    }),
                                JsxRuntime.jsx("option", {
                                      children: "Higiene",
                                      value: "Higiene"
                                    }),
                                JsxRuntime.jsx("option", {
                                      children: "Limpeza",
                                      value: "Limpeza"
                                    })
                              ],
                              value: category,
                              onChange: (function ($$event) {
                                  setCategory(function (param) {
                                        return $$event.target.value;
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Adicionar",
                              onClick: addItem
                            })
                      ],
                      style: style
                    }),
                JsxRuntime.jsx("ul", {
                      children: match[0].map(function (i) {
                            return JsxRuntime.jsxs("li", {
                                        children: [
                                          JsxRuntime.jsx("input", {
                                                type: "checkbox",
                                                onChange: (function (param) {
                                                    var id = i.id;
                                                    setItems(function (prev) {
                                                          return prev.filter(function (i) {
                                                                      return i.id !== id;
                                                                    });
                                                        });
                                                  })
                                              }),
                                          i.name + " (" + i.category + ")"
                                        ]
                                      }, String(i.id));
                          })
                    })
              ]
            });
}

var make = ShoppingList;

export {
  style ,
  make ,
}
/* react Not a pure module */
